version: '3'

services:

 elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elastic
    environment:
      cluster.name: bills-processer
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local


